using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using SqlAssist.Core.Json;

namespace SqlAssist.TextGenerator;

/// <summary>把 <c>&lt;類別&gt;.&lt;語言&gt;.resjson</c> 轉成強型別的文字存取類別。</summary>
/// <remarks>
/// 每一句文字編成一個陣列，依語言清單的順序排，執行期以目前語言的索引取值：
/// 沒有衛星組件、沒有執行期剖析，隔離 AppDomain 與 VSIX 探測路徑都碰不到它。
/// 有佔位符的句子產生成方法，參數個數由編譯器檢查；各語言的鍵與佔位符不一致是建置錯誤，
/// 不在執行期退回來源語言。
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class SqlTextGenerator : IIncrementalGenerator
{
    internal const string FileExtension = ".resjson";
    private const string LanguagesProperty = "build_property.SqlAssistTextLanguages";
    private const string LanguagesAttribute = "SqlAssist.Core.Localization.SqlTextLanguagesAttribute";
    private const string Runtime = "global::SqlAssist.Core.Localization.SqlText";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var languages = context.AnalyzerConfigOptionsProvider.Select(
            (provider, _) => provider.GlobalOptions.TryGetValue(LanguagesProperty, out var value) ? value : string.Empty);
        var files = context.AdditionalTextsProvider
            .Where(file => file.Path.EndsWith(FileExtension, StringComparison.OrdinalIgnoreCase))
            .Select((file, token) => new InputFile(file.Path, file.GetText(token)?.ToString() ?? string.Empty));
        var hasAttribute = context.CompilationProvider.Select(
            (compilation, _) => compilation.GetTypeByMetadataName(LanguagesAttribute) is not null);

        context.RegisterSourceOutput(
            files.Collect().Combine(languages).Combine(hasAttribute),
            (output, input) => Execute(output, input.Left.Left, ParseLanguages(input.Left.Right), input.Right));
    }

    internal static ImmutableArray<string> ParseLanguages(string value) =>
        value.Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries)
            .Select(language => language.Trim())
            .Where(language => language.Length > 0)
            .ToImmutableArray();

    private static void Execute(
        SourceProductionContext output,
        ImmutableArray<InputFile> files,
        ImmutableArray<string> languages,
        bool hasAttribute)
    {
        if (hasAttribute && languages.Length > 0)
        {
            // 語言清單的唯一來源是 MSBuild 屬性；Core 從自己的這一行讀出執行期的語言表，
            // 所以陣列的索引順序與 SqlLanguage.Index 不會各記一份。
            var names = string.Join(", ", languages.Select(Literal));
            output.AddSource(
                "SqlTextLanguages.g.cs",
                $"// <auto-generated/>\n[assembly: global::{LanguagesAttribute}({names})]\n");
        }

        if (files.IsEmpty)
        {
            return;
        }

        if (languages.IsEmpty)
        {
            output.ReportDiagnostic(Diagnostic.Create(SqlTextDiagnostics.NoLanguages, Location.None));
            return;
        }

        var groups = new SortedDictionary<string, TextGroup>(StringComparer.Ordinal);
        foreach (var file in files)
        {
            var name = Path.GetFileName(file.Path);
            var stem = name.Substring(0, name.Length - FileExtension.Length);
            var dot = stem.LastIndexOf('.');
            var className = dot > 0 ? stem.Substring(0, dot) : string.Empty;
            var language = dot > 0 ? stem.Substring(dot + 1) : string.Empty;
            if (!SqlTextTemplate.IsKeyName(className) || !languages.Contains(language))
            {
                output.ReportDiagnostic(Diagnostic.Create(
                    SqlTextDiagnostics.BadFileName,
                    FileLocation(file.Path),
                    name,
                    string.Join("、", languages)));
                continue;
            }

            var directory = Path.GetDirectoryName(file.Path) ?? string.Empty;
            var groupKey = directory + "|" + className;
            if (!groups.TryGetValue(groupKey, out var group))
            {
                group = new TextGroup(directory, className);
                groups.Add(groupKey, group);
            }

            group.Files[language] = file;
        }

        foreach (var group in groups.Values)
        {
            Emit(output, group, languages);
        }
    }

    private static void Emit(SourceProductionContext output, TextGroup group, ImmutableArray<string> languages)
    {
        var anyFile = group.Files.Values.First();
        var ns = NamespaceOf(group.Directory);
        if (ns is null)
        {
            output.ReportDiagnostic(Diagnostic.Create(SqlTextDiagnostics.BadNamespace, FileLocation(anyFile.Path), anyFile.Path));
            return;
        }

        var tables = new Dictionary<string, TextTable>();
        foreach (var language in languages)
        {
            if (!group.Files.TryGetValue(language, out var file))
            {
                output.ReportDiagnostic(Diagnostic.Create(
                    SqlTextDiagnostics.MissingLanguage, FileLocation(anyFile.Path), group.ClassName, language));
                continue;
            }

            var table = TextTable.Read(file, output);
            if (table is not null)
            {
                tables[language] = table;
            }
        }

        var sourceLanguage = languages[0];
        if (!tables.TryGetValue(sourceLanguage, out var source))
        {
            return;
        }

        var members = new List<TextMember>();
        foreach (var key in source.Keys)
        {
            var sourceEntry = source.Entries[key];
            if (!SqlTextTemplate.IsKeyName(key))
            {
                output.ReportDiagnostic(Diagnostic.Create(SqlTextDiagnostics.BadKey, source.LocationOf(key), key));
                continue;
            }

            var sourceTemplate = SqlTextTemplate.Parse(sourceEntry, out var sourceError);
            if (sourceTemplate is null)
            {
                output.ReportDiagnostic(Diagnostic.Create(SqlTextDiagnostics.BadTemplate, source.LocationOf(key), key, sourceError));
                continue;
            }

            var order = sourceTemplate.Names;
            var values = new string[languages.Length];
            for (var i = 0; i < languages.Length; i++)
            {
                var template = sourceTemplate;
                if (i > 0 && tables.TryGetValue(languages[i], out var table))
                {
                    template = Translated(output, group.ClassName, languages[i], table, key, sourceTemplate) ?? sourceTemplate;
                }

                values[i] = order.Count == 0 ? template.ToPlainText() : template.ToCompositeFormat(order);
            }

            members.Add(new TextMember(key, sourceEntry, order, values));
        }

        for (var i = 1; i < languages.Length; i++)
        {
            if (!tables.TryGetValue(languages[i], out var table))
            {
                continue;
            }

            foreach (var key in table.Keys.Where(key => !source.Entries.ContainsKey(key)))
            {
                output.ReportDiagnostic(Diagnostic.Create(
                    SqlTextDiagnostics.ExtraKey, table.LocationOf(key), group.ClassName, languages[i], key));
            }
        }

        output.AddSource($"{ns}.{group.ClassName}.g.cs", Render(ns, group.ClassName, members));
    }

    private static SqlTextTemplate? Translated(
        SourceProductionContext output,
        string className,
        string language,
        TextTable table,
        string key,
        SqlTextTemplate source)
    {
        if (!table.Entries.TryGetValue(key, out var text))
        {
            output.ReportDiagnostic(Diagnostic.Create(
                SqlTextDiagnostics.MissingKey, table.FirstLocation(), className, language, key));
            return null;
        }

        var template = SqlTextTemplate.Parse(text, out var error);
        if (template is null)
        {
            output.ReportDiagnostic(Diagnostic.Create(SqlTextDiagnostics.BadTemplate, table.LocationOf(key), key, error));
            return null;
        }

        if (!template.Names.OrderBy(name => name, StringComparer.Ordinal)
                .SequenceEqual(source.Names.OrderBy(name => name, StringComparer.Ordinal)))
        {
            output.ReportDiagnostic(Diagnostic.Create(
                SqlTextDiagnostics.PlaceholderMismatch,
                table.LocationOf(key),
                className,
                language,
                key,
                Describe(template.Names),
                Describe(source.Names)));
            return null;
        }

        return template;
    }

    private static string Render(string ns, string className, IReadOnlyList<TextMember> members)
    {
        var builder = new StringBuilder();
        builder.Append("// <auto-generated/>\n#nullable enable\n\nnamespace ").Append(ns).Append("\n{\n");
        builder.Append("    public static partial class ").Append(className).Append("\n    {\n");
        foreach (var member in members)
        {
            builder.Append("        /// <summary>").Append(XmlText(member.Summary)).Append("</summary>\n");
            if (member.Parameters.Count == 0)
            {
                builder.Append("        public static string ").Append(member.Key)
                    .Append(" => ").Append(Runtime).Append(".Pick(s_").Append(member.Key).Append(");\n\n");
                continue;
            }

            var parameters = string.Join(", ", member.Parameters.Select(name => "object? " + Identifier(name)));
            var arguments = string.Join(", ", member.Parameters.Select(Identifier));
            builder.Append("        public static string ").Append(member.Key).Append('(').Append(parameters)
                .Append(") => ").Append(Runtime).Append(".Format(s_").Append(member.Key).Append(", ")
                .Append(arguments).Append(");\n\n");
        }

        foreach (var member in members)
        {
            builder.Append("        private static readonly string[] s_").Append(member.Key).Append(" = { ")
                .Append(string.Join(", ", member.Values.Select(Literal))).Append(" };\n");
        }

        builder.Append("    }\n}\n");
        return builder.ToString();
    }

    /// <summary>由 <c>src/&lt;專案&gt;/&lt;資料夾&gt;</c> 推出命名空間；連結進測試專案的檔案實體路徑不變，推出來的也一樣。</summary>
    internal static string? NamespaceOf(string directory)
    {
        var segments = directory.Split(new[] { '\\', '/' }, StringSplitOptions.RemoveEmptyEntries);
        var root = Array.FindLastIndex(segments, segment => string.Equals(segment, "src", StringComparison.OrdinalIgnoreCase));
        return root < 0 || root == segments.Length - 1
            ? null
            : string.Join(".", segments.Skip(root + 1));
    }

    private static string Identifier(string name) =>
        SyntaxFacts.GetKeywordKind(name) == SyntaxKind.None ? name : "@" + name;

    private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, quote: true);

    private static string Describe(IReadOnlyList<string> names) =>
        names.Count == 0 ? "（無）" : string.Join("、", names.Select(name => "{" + name + "}"));

    private static string XmlText(string value) =>
        value.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;")
            .Replace("\r", string.Empty).Replace("\n", " ");

    private static Location FileLocation(string path) =>
        Location.Create(path, default, new LinePositionSpan(default, default));

    internal sealed class InputFile : IEquatable<InputFile>
    {
        public InputFile(string path, string text)
        {
            Path = path;
            Text = text;
        }

        public string Path { get; }

        public string Text { get; }

        public bool Equals(InputFile? other) =>
            other is not null && other.Path == Path && other.Text == Text;

        public override bool Equals(object? obj) => Equals(obj as InputFile);

        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Path) ^ StringComparer.Ordinal.GetHashCode(Text);
    }

    private sealed class TextGroup
    {
        public TextGroup(string directory, string className)
        {
            Directory = directory;
            ClassName = className;
        }

        public string Directory { get; }

        public string ClassName { get; }

        public Dictionary<string, InputFile> Files { get; } = new(StringComparer.Ordinal);
    }

    private sealed class TextMember
    {
        public TextMember(string key, string summary, IReadOnlyList<string> parameters, string[] values)
        {
            Key = key;
            Summary = summary;
            Parameters = parameters;
            Values = values;
        }

        public string Key { get; }

        public string Summary { get; }

        public IReadOnlyList<string> Parameters { get; }

        public string[] Values { get; }
    }

    /// <summary>一份 .resjson：扁平的「鍵 → 文字」物件，可以寫 // 註解給譯者看。</summary>
    private sealed class TextTable
    {
        private readonly InputFile _file;

        private TextTable(InputFile file, Dictionary<string, string> entries)
        {
            _file = file;
            Entries = entries;
            Keys = entries.Keys.OrderBy(key => key, StringComparer.Ordinal).ToList();
        }

        public Dictionary<string, string> Entries { get; }

        public IReadOnlyList<string> Keys { get; }

        public static TextTable? Read(InputFile file, SourceProductionContext output)
        {
            JsonValue root;
            try
            {
                root = JsonReader.Parse(file.Text);
            }
            catch (JsonParseException exception)
            {
                output.ReportDiagnostic(Diagnostic.Create(
                    SqlTextDiagnostics.BadJson,
                    LocationAt(file, exception.Position, 1),
                    exception.Message));
                return null;
            }

            if (root.Kind != JsonKind.Object)
            {
                output.ReportDiagnostic(Diagnostic.Create(
                    SqlTextDiagnostics.BadJson, FileLocation(file.Path), "最外層必須是 { \"鍵\": \"文字\" } 物件"));
                return null;
            }

            var entries = new Dictionary<string, string>(StringComparer.Ordinal);
            foreach (var name in root.Names)
            {
                var value = root[name];
                if (value.Kind != JsonKind.String)
                {
                    output.ReportDiagnostic(Diagnostic.Create(
                        SqlTextDiagnostics.BadJson, FileLocation(file.Path), $"鍵 '{name}' 的值必須是字串"));
                    continue;
                }

                entries[name] = value.AsString();
            }

            return new TextTable(file, entries);
        }

        public Location LocationOf(string key)
        {
            var quoted = "\"" + key + "\"";
            var position = _file.Text.IndexOf(quoted, StringComparison.Ordinal);
            return position < 0 ? FirstLocation() : LocationAt(_file, position, quoted.Length);
        }

        public Location FirstLocation() => FileLocation(_file.Path);

        private static Location LocationAt(InputFile file, int position, int length)
        {
            var text = SourceText.From(file.Text);
            position = Math.Max(0, Math.Min(position, text.Length));
            var span = new TextSpan(position, Math.Min(length, text.Length - position));
            return Location.Create(file.Path, span, text.Lines.GetLinePositionSpan(span));
        }
    }
}
